/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorModulos.h"


void autorizar_usuarios_1(char *host)
{
	char* identificacion;
	CLIENT *clnt;
	nodo_turno  *result_1;
	char * generarturno_1_arg;
	
	#ifndef	DEBUG
	clnt = clnt_create (host, autorizar_usuarios, autorizar_usuarios_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */
	
	result_1 = generarturno_1(&generarturno_1_arg, clnt);
	if (result_1 == (nodo_turno *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
	/*Llamado al procesamiento para generar el turno*/
	identificacion = (char*) malloc(50*sizeof(char));
	printf("=== Sistema para la generacion de turnos ===");
	printf("\n Digite la identificacion: ");
	scanf("%s", identificacion);
	result_1 = generarturno_1(&identificacion, clnt);
	if (result_1 == (nodo_turno *) NULL)
	{
		clnt_perror (clnt, "call failed");
	}
	/*Resultado que genera la invocacion al procesamiento remoto*/
	else
	{
		printf("\n === Datos generados por el sistema ===");
		printf("Numero de identificacion: %s", (*result_1).identificacionUsuario);
		printf("Numero de turno: %s", (*result_1).numeroTurno);
		printf("Cantidad de usuarios en la fila virtual: %d", (*result_1).cantidadUsuariosFilaVirtual);
		printf("\n");
	}
	
	#ifndef	DEBUG
	clnt_destroy (clnt);
	#endif	 /* DEBUG */
	
}


int main (int argc, char *argv[])
{
	int opcion;
	char *host;

	do
	{
		printf("=== Menu sistema para la generacion de turnos === \n");
		printf("1. Generar turno.\n");
		printf("2. Salir. \n");
		printf("=================================================\n");

		if (argc < 2) {
			printf ("usage: %s server_host\n", argv[0]);
			exit (1);
		}
		scanf("%d", opcion);
		host = argv[1];
		autorizar_usuarios_1 (host);
	} while (opcion != 2);

	exit (0);
}

