/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "InterfaceClienteServidorModulos.h"

bool_t
xdr_nodo_turno (XDR *xdrs, nodo_turno *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numeroTurno))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantidadUsuariosFilaVirtual))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->identificacionUsuario, MAXIDENTIFICACION,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
