/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACECLIENTESERVIDORMODULOS_H_RPCGEN
#define _INTERFACECLIENTESERVIDORMODULOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXIDENTIFICACION 10

struct nodo_turno {
	int numeroTurno;
	int cantidadUsuariosFilaVirtual;
	char identificacionUsuario[MAXIDENTIFICACION];
};
typedef struct nodo_turno nodo_turno;

#define autorizar_usuarios 0x20000001
#define autorizar_usuarios_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define generarTurno 1
extern  nodo_turno * generarturno_1(char **, CLIENT *);
extern  nodo_turno * generarturno_1_svc(char **, struct svc_req *);
extern int autorizar_usuarios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define generarTurno 1
extern  nodo_turno * generarturno_1();
extern  nodo_turno * generarturno_1_svc();
extern int autorizar_usuarios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_turno (XDR *, nodo_turno*);

#else /* K&R C */
extern bool_t xdr_nodo_turno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACECLIENTESERVIDORMODULOS_H_RPCGEN */
