/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "InterfaceClienteServidorModulos.h"
#include <stdbool.h>


struct modulo {
	bool ocupado;
	int numeroTurno;
	char identificacionUsuario[MAXIDENTIFICACION];

};

typedef struct modulo modulo;

struct usuario{
	char identificacionUsuario[MAXIDENTIFICACION];
};

typedef struct usuario usuario;
int consultarNUmeroModuloDisponible();
int numeroTurno =1;
int cantidadUsuariosFila = 0;
modulo vectorModulos[3];
usuario filaVirtual[10];

nodo_turno *  generarturno_1_svc(char **argp, struct svc_req *rqstp)
{
	static nodo_turno  result;

	int posicion = consultarNUmeroModuloDisponible();
	printf("\n");
	if(posicion==-1){
		printf("\n Los modulos se encuentran ocupados");
		strcpy(filaVirtual[cantidadUsuariosFila].identificacionUsuario,*argp);
		cantidadUsuariosFila ++; 
		printf("\n El usuario se agrego a la fila virtual.");
	}else{
		printf("\n EL modulo en la poscion %d esta libre y se asignara al usuario con identificacion %s",(posicion+1),*argp);
		vectorModulos[posicion].ocupado = true;
		vectorModulos[posicion].numeroTurno = numeroTurno;
		strcpy(vectorModulos[posicion].identificacionUsuario,*argp);
	}
	result.numeroTurno = numeroTurno;
	result.cantidadUsuariosFilaVirtual = cantidadUsuariosFila;
	strcpy(result.identificacionUsuario,*argp);
	numeroTurno ++;
	printf("\n"); 
	return &result;
}

int consultarNUmeroModuloDisponible(){
	int posicion = -1;
	for(int i=0; i<3; i++){
		if(vectorModulos[i].ocupado ==false){
			posicion = i;
			break;
		}
	}
	return posicion; 
}
